import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const DemoVideo: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Caramel Club - Laugh at comedy, get dates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Demo Video</h1>
      </main>

      <footer className={styles.footer}>
        <ul>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              home
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              contact
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              legal
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              privacy
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
};

export default DemoVideo;
