import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/video.module.scss";

const DemoVideo: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Caramel Club - Laugh at comedy, get dates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Demo Video</h1>
        <div className={styles["hero-section"]}>
          <div className={styles["demo-frame"]}>
            <Image
              src="/iphone-frame-2.png"
              alt="iPhone Frame"
              layout="fixed"
              width="330px"
              height="645px"
            />
          </div>
          <div className={styles["demo-gif"]}>
            <Image
              src="/aws-founders-demo.gif"
              alt="Demo GIF"
              layout="fixed"
              width="330px"
              height="645px"
            />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <ul>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              home
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              contact
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              legal
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              privacy
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
};

export default DemoVideo;
