import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.scss";
// import demoGif from "../public/aws-founders-demo.gif";

type StepProps = {
  title: string;
  subtext: string;
  number: string;
};

const Step = ({ title, subtext, number }: StepProps) => (
  <div className={styles["step"]}>
    <div className={styles["circle"]}>{number}</div>
    <p className={styles["title"]}>{title}</p>
    <p className={styles["subtext"]}>{subtext}</p>
  </div>
);

const Home: NextPage = () => {
  useEffect(() => {
    Router.push("https://tally.so/r/mD4o6N");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Caramel Club - Laugh at comedy, get dates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles["hero-section"]}>
          <div className={styles["demo-frame"]}>
            <Image
              src="/iphone-frame-2.png"
              alt="iPhone Frame"
              layout="fixed"
              width="330px"
              height="645px"
            />
          </div>
          <div className={styles["demo-gif"]}>
            <Image
              src="/aws-founders-demo.gif"
              alt="Demo GIF"
              layout="fixed"
              width="330px"
              height="645px"
            />
          </div>
          <div className={styles["hero-content"]}>
            <Image
              src="/caramelclub-logo.svg"
              alt="Logo"
              layout="fixed"
              width="290px"
              height="162px"
            />
            <div className={styles["hero-content-text"]}>
              <h1>Watch standup, find dates</h1>
              <ul>
                <li>Match with people who laugh at the same stuff</li>
                <li>No app download necessary</li>
                <li>Everything is done over SMS</li>
                <li>Your real phone number is hidden</li>
              </ul>
              <button
                onClick={() => (document.location.href = "sms:9739347213")}
              >
                <b>Get started</b>
              </button>
              <p>Or text LMAO to 973-934-7213</p>
            </div>
          </div>
        </div>
        <div className={styles["steps-to-value-section"]}>
          <Step title="Sign up" subtext="Just text 973-934-7213" number="1" />
          <Step
            title="Watch some comedy"
            subtext="We'll send you links to videos and you can rate them"
            number="2"
          />
          <Step
            title="Sign up"
            subtext="If you and another person like the same thing, we'll connect you two"
            number="3"
          />
        </div>
        <h1 className={styles.title}></h1>
      </main>

      <footer className={styles.footer}>
        <ul>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              home
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              contact
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              legal
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              privacy
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
};

export default Home;
