import type { NextPage } from "next";
import Router from "next/router";
import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/video.module.scss";

const TryForm: NextPage = () => {
  useEffect(() => {
    Router.push("https://tally.so/r/mD4o6N");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Caramel Club - Laugh at comedy, get dates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <a href="https://tally.so/r/mD4o6N"> form</a>
        </div>
      </main>

      <footer className={styles.footer}>
        <ul>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              home
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              contact
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              legal
            </a>
          </li>
          <li>
            <a target="#blank" href="" rel="noopener noreferrer">
              privacy
            </a>
          </li>
        </ul>
      </footer>
    </div>
  );
};

export default TryForm;
